name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # - name: Generate build number
    #   uses: einaregilsson/build-number@v3
    #   with:
    #     token: ${{secrets.API_TOKEN_GITHUB}}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish -c "Release" --self-contained false
      
    - name: Deploy
      uses: drud/action-cross-commit@master
      with:
        source-folder: bin/Release/net5.0/publish
        destination-repository: https://KrishnaAchuthan:${{ secrets.API_TOKEN_GITHUB }}@github.com/KrishnaAchuthan/poll-deploy.git
        destination-folder: ./publish
        destination-branch: main
        git-user: "Actions"
        git-user-email: infinitewormhole@gmail.com
        git-commit-message: "Automated Build"
        git-commit-sign-off: "false"
        excludes: README.md